name: Docker Build and scan
on:
  push:
    branches:
      - "main"
jobs:
  docker_build:
    name: "Build docker deploy to docker hub"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build, tag, and push image to Docker hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t v3dotcash/elixir-redhat-builder:latest .
          echo "::set-output name=v3dotcash/elixir-redhat-builder:latest"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: 'v3dotcash/elixir-redhat-builder:latest'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'